env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  linebreak-style:
    - error
    - unix
  "@typescript-eslint/ban-ts-comment": "off"
  "@typescript-eslint/no-explicit-any": "off"
overrides:
  - files: 
    - "*.js"
    - "*.jsx"
    rules:
      "@typescript-eslint/...": "off"