image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      yarn install
      ./generate_protos.sh
    command: |
      yarn start
vscode:
  extensions:
    - jpoissonnier.vscode-styled-components
    - esbenp.prettier-vscode
