image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      yarn install
    command: |
      ./generate_protos.sh
      yarn start

vscode:
  extensions:
    - jpoissonnier.vscode-styled-components
    - esbenp.prettier-vscode
